routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('ajax_test', 'HomeController@ajax_test')->name('ajax_test');

 //get tags via ajax
	Route::get('/get_tags', 'TutorialsController@get_tags')->name('get_tags');
	Route::get('/get_auth_skills', 'UserController@get_auth_skills')->name('get_auth_skills');
	
	
Route::get('/logout', 'HomeController@logout')->name('logout');


//Route::get('dashboard', ['middleware' => 'auth', 'uses' => 'UserController@getDashboard', 'as' => 'user.dashboard',]);
Route::group( ['middleware' => ['auth']], function() {
	Route::get('/users/{role}', 'UserController@users_by_role')->name('users_by_role');
    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
	Route::resource('contact_types', 'ContactTypeController');
	 
	Route::resource('credentials_types', 'CredentialsTypesController');
	Route::resource('urls_types', 'UrlsTypesController');
	Route::resource('urls', 'UrlsController');
	Route::get('/urls/analytics/{urlId}', 'UrlsController@get_analytics');
		
	Route::resource('payment_modes', 'PaymentModesController');
	Route::resource('payment_fee_types', 'PaymentFeeTypesController');
	
	Route::resource('designations', 'DesignationsController');
	Route::resource('card_issue_types', 'CardIssueTypesController');
	Route::resource('employee_designations', 'EmployeeDesignationsController');
	
	Route::post('add_issue_type', 'CardIssueTypesController@add_issue_type')->name('add_issue_type');
	
	Route::resource('tutorials', 'TutorialsController');
	//Route::get('add_tutorials', function () {    return view('tutorials.new');})->name("add_tutorials");
	Route::get('add_tutorials', 'TutorialsController@create')->name('add_tutorials');
	Route::post('get_tutorials', 'TutorialsController@get_tutorials')->name('get_tutorials');
	
	Route::get('get_tutorials_list', 'TutorialsController@get_tutorials_list')->name('get_tutorials_list');
	
	Route::resource('contacts', 'ContactController');
	Route::resource('projects', 'ProjectController');
	
	Route::resource('realtimeboards', 'ProjectRealTimeController');
	Route::resource('trelloboards', 'ProjectTrelloController');
	Route::resource('credentials', 'ProjectCredentialsController');
	Route::resource('notes', 'ProjectNotesController');
	
	Route::get('/get_auth_skills', 'UserController@get_auth_skills')->name('get_auth_skills');
	
   
	
	Route::get('/projects_list/projects_by_status/{status}', 'ProjectController@projects_by_status')->name('projects_by_status');
	Route::get('/project_details/realtimeboards/{id}', 'ProjectController@show_realtimeboard')->name('show_realtimeboard');
	Route::get('/project_details/trelloboards/{id}', 'ProjectController@show_trelloboard')->name('show_trelloboard');
	Route::get('/project_details/credentials/{id}', 'ProjectController@show_credentials')->name('show_credentials');
	Route::get('/project_details/notes/{id}', 'ProjectController@show_notes')->name('show_notes');
	Route::get('/project_details/drives/{id}', 'ProjectController@show_google_drives')->name('show_google_drives');
	Route::get('/project_details/cards/{id}', 'BoardController@show_cards')->name('show_cards');
	
	
	Route::get('/users/show_edit_user_profile/{id}', 'UserController@show_edit_user_profile')->name('show_edit_user_profile');
	Route::post('/users/update_edit_user_profile/', 'UserController@update_edit_user_profile')->name('update_edit_user_profile');
	
	Route::post('/projects_by_employee/', 'ProjectController@projects_by_employee')->name('projects_by_employee');
	
	//contacts starts
	Route::get('/contacts/{role}/{linked_id}', 'ContactController@index')->name('get_contacts');
	
	
});


 
Route::get('downloadExcel/{role}/xls', 'UserController@downloadExcelByRole');
Route::get('downloadExcel/xls', 'UserController@downloadExcelAll');
 
Route::get('downloadExcelProject/{role}/xls', 'ProjectController@downloadExcelByRole');
Route::get('downloadExcelProject/xls', 'ProjectController@downloadExcelAll');

Route::post('importExcel', 'ExportController@importExcel');




Route::get('register', ['middleware' => 'guest', 'uses' => 'UserController@getRegister', 'as' => 'auth.register',]);
Route::post('register', ['middleware' => 'guest', 'uses' => 'UserController@postRegister',]);
Route::get('dashboard', ['middleware' => 'auth', 'uses' => 'UserController@getDashboard', 'as' => 'user.dashboard',]);
Route::get('profile', ['middleware' => 'auth', 'uses' => 'UserController@getProfile', 'as' => 'user.profile',]);
Route::get('activity', ['middleware' => 'auth', 'uses' => 'UserActivityController@getUserActivity', 'as' => 'user.activity',]);

Route::post('postBoard', ['middleware' => 'auth', 'uses' => 'BoardController@postBoard',]);
Route::post('update-board-favourite', ['middleware' => 'auth', 'uses' => 'BoardController@updateBoardFavourite',]);

/**
 * Board
 */
Route::group(
    ['prefix' => 'board'],
    function () {
        
		Route::post('/postListName', ['uses' => 'ListController@postListName',]);
        
		Route::post('/delete-list', ['uses' => 'ListController@deleteList',]);
        
		Route::post('/update-list-name', ['uses' => 'ListController@updateListName',]);

        Route::post('/postCard', ['uses' => 'CardController@postCard',]);
        
		Route::post('/getPusherData', ['uses' => 'BoardController@getPusherData',]);
				
        Route::post('/changeCardList', ['uses' => 'CardController@changeCardList',]);
        
		Route::post('/deleteCard', ['uses' => 'CardController@deleteCard',]);
        
		Route::post('/getCardDetail', ['uses' => 'CardController@getCardDetail',]);
        
		Route::post('/update-card-data', ['uses' => 'CardController@updateCardData',]);

        Route::post('/save-comment', ['uses' => 'CommentController@saveComment',]);

        Route::post('/save-task', ['uses' => 'TaskController@saveTask',]);
        
		Route::post('/delete-task', ['uses' => 'TaskController@deleteTask',]);
        
		Route::post('/update-task-completed', ['uses' => 'TaskController@updateTaskCompleted',]);
		
		Route::post('/file_uploader', ['uses' => 'FileUploader@file_uploader',])->name('file_uploader');

        Route::get('/{id?}', ['middleware' => 'auth', 'uses' => 'BoardController@getBoardDetail', 'as' => 'user.boardDetail',]);
		
 
		
		Route::get('/project_details/cards/{id?}', ['middleware' => 'auth', 'uses' => 'BoardController@getBoardDetailProject', 'as' => 'user.boardDetail',]);
		
		Route::post('/cards-filter', ['middleware' => 'auth', 'uses' => 'BoardController@getBoardDetailFiltered', 'as' => 'user.cards-filter',]);
		
		Route::get('/duedate/{id?}', ['middleware' => 'auth', 'uses' => 'BoardController@getBoardDetail', 'as' => 'user.boardDetail',]);
        
		Route::post('create-user-activity', ['uses' => 'UserActivityController@createUserActivity']);
    }
);

/**
 * Password Reset
 */
Route::group(
    ['prefix' => 'password'],
    function () {
        // Password reset link request routes...
        Route::get('/email', 'Auth\PasswordController@getEmail');
        Route::post('/email', 'Auth\PasswordController@postEmail');

        // Password reset routes...
        Route::get('/reset/{token}', 'Auth\PasswordController@getReset');
        Route::post('/reset', 'Auth\PasswordController@postReset');
    }
);

Route::post('create-user-activity', ['uses' => 'UserActivityController@createUserActivity']);



Route::get('test/{cardId}', function ($cardId) {
	 
    event(new App\Events\StatusLiked($cardId));
    return "Event has been sent!";
});
 

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
  protected $fillable = ['project_title','project_start_date','slack_channel_id','status','drive_admin_folder','drive_development_folder'];
 
 
    public function ProjectRealTimeBoard()
    {
        return $this->hasMany(ProjectRealTimeBoard::class);
    }
	
	
	public function ProjectTrelloBoard()
    {
        return $this->hasMany(ProjectTrelloBoard::class);
    }
	
		public function Credentials()
    {
        return $this->hasMany(Credentials::class);
    }
	
	
			public function Notes()
    {
        return $this->hasMany(Notes::class , 'linked_id','id');
    }
	
		    public function project_employees()
    {
        return $this->hasMany(ProjectEmployees::class);
    }
	
}

resources/views/projects/_form.blade.php
<!-- First Name Form Input -->
 

<div class="form-group @if ($errors->has('project_title')) has-error @endif">
    {!! Form::label('project_title', 'Project Title') !!}
    {!! Form::text('project_title', @$project_title, ['class' => 'form-control ', 'placeholder' => 'Project Title' ] ) !!}
    @if ($errors->has('project_title')) <p class="help-block">{{ $errors->first('project_title') }}</p> @endif
</div>


<div class="form-group @if ($errors->has('project_start_date')) has-error @endif">
    {!! Form::label('project_start_date', 'Project Start Date') !!}
    {!! Form::text('project_start_date', @$project_start_date, ['class' => 'form-control datetimepicker', 'placeholder' => 'Project Start Date' ] ) !!}
    @if ($errors->has('project_start_date')) <p class="help-block">{{ $errors->first('project_start_date') }}</p> @endif
</div>


<div class="form-group @if ($errors->has('slack_channel_id')) has-error @endif">
    {!! Form::label('slack_channel_id', 'Slack Channel Id') !!}
    {!! Form::text('slack_channel_id', @$slack_channel_id, ['class' => 'form-control', 'placeholder' => 'Slack Channel Id' ] ) !!}
    @if ($errors->has('slack_channel_id')) <p class="help-block">{{ $errors->first('slack_channel_id') }}</p> @endif
</div>

<div class="form-group @if ($errors->has('drive_admin_folder')) has-error @endif">
    {!! Form::label('drive_admin_folder', 'Drive Admin Folder') !!}
    {!! Form::text('drive_admin_folder', @$drive_admin_folder, ['class' => 'form-control', 'placeholder' => 'Drive Admin Folder' ] ) !!}
    @if ($errors->has('drive_admin_folder')) <p class="help-block">{{ $errors->first('drive_admin_folder') }}</p> @endif
</div>

<div class="form-group @if ($errors->has('drive_development_folder')) has-error @endif">
    {!! Form::label('drive_development_folder', 'Drive Development Folder') !!}
    {!! Form::text('drive_development_folder', @$drive_development_folder, ['class' => 'form-control', 'placeholder' => 'Drive Development Folder' ] ) !!}
    @if ($errors->has('drive_development_folder')) <p class="help-block">{{ $errors->first('drive_development_folder') }}</p> @endif
</div>

 


<div class="form-group @if ($errors->has('status')) has-error @endif">
{!! Form::label('status', 'Project Status') !!}
 {{$errors->has('status')}}
<select class="form-control" name="status" id="status" required >
<option value="">Select Project Status</option>      
<option value="0" <?php if(isset($id) && \App\Project::where('id',@$id)->first(["status"])->status=='0'){ echo 'SELECTED';} ?> >Work Pending</option>
<option value="1" <?php if(isset($id) && \App\Project::where('id',@$id)->first(["status"])->status=='1'){ echo 'SELECTED';} ?>>Team Working</option>
<option value="2" <?php if( isset($id) &&\App\Project::where('id',@$id)->first(["status"])->status=='2'){ echo 'SELECTED';} ?>>Waiting For Client</option>
<option value="3" <?php if( isset($id) &&\App\Project::where('id',@$id)->first(["status"])->status=='3'){ echo 'SELECTED';} ?>>Completed</option>
<option value="4" <?php if( isset($id) &&\App\Project::where('id',@$id)->first(["status"])->status=='4'){ echo 'SELECTED';} ?>>Cancelled</option>
<option value="4" <?php if( isset($id) &&\App\Project::where('id',@$id)->first(["status"])->status=='5'){ echo 'SELECTED';} ?>>Payment Pending</option>
 </select>
   @if ($errors->has('status')) <p class="help-block">{{ $errors->first('status') }}</p> @endif
</div>

 
 
 




 
<div class="form-group @if ($errors->has('employees_array')) has-error @endif">
{!! Form::label('employees_array', 'Employees') !!}

 
   <select   class="form-control" id="example-getting-started" name="employees_array[]" multiple="multiple" style="width:100%">
    
      @foreach($employees_array as $ct)
	  
	  	<?php   $count1 = \App\ProjectEmployees::where('project_id',@$id)->where('employee_id',@$ct->id)->get();
		if(isset($id) && $count1->count() > 0 ) { $s1 = 'SELECTED';} else { $s1 = '';}
		?>
         <option value="{{ $ct->id }}" <?php echo $s1;?> >{{ $ct->first_name." ".$ct->last_name  }}</option>
     @endforeach
</select>
</div>




<div class="form-group @if ($errors->has('clients_array')) has-error @endif">
    {!! Form::label('employees', 'Clients') !!}
   <select  class="form-control" id="example-getting-started2" name="clients_array[]"  multiple="multiple">
     @foreach($clients_array as $ct2)
	<?php   $count2 = \App\ProjectClients::where('project_id',@$id)->where('client_id',$ct2->id)->get();
		if(isset($id) && $count2->count() > 0 ) { $s2 = 'SELECTED';} else { $s2 = '';}
		?>
	     <option value="{{ $ct2->id }}" <?php echo $s2;?>  >{{ $ct2->first_name }}</option>
     @endforeach
</select>
</div>
 

<script type="text/javascript">
   $(document).ready(function() {
       $('#example-getting-started').multiselect({enableFiltering: true,enableFullValueFiltering:true,enableCaseInsensitiveFiltering:true,selectAllNumber:true,
	   numberDisplayed: 100,filterBehavior: 'text'});
	   $('#example-getting-started2').multiselect({enableFiltering: true,enableFullValueFiltering:true,enableCaseInsensitiveFiltering:true,selectAllNumber:true,
	   numberDisplayed: 100,filterBehavior: 'text'});
 });
</script>

 

 
<script type='text/javascript'>
$(window).load(function(){
$('.datetimepicker').datetimepicker({  format:'DD/MM/YYYY hh:mm A', });
 
});
</script>

resources/views/projects/_form_credentials.blade.php
<!-- First Name Form Input -->
 

{!! Form::hidden('project_id', @$id, [] ) !!}
	
	
<div class="form-group @if ($errors->has('title')) has-error @endif">
    {!! Form::label('title', 'Type') !!}
	
	<?php $credentials_types = \App\CredentialsTypes::get(); ?>
	<select name="credentials_type_id" class="form-control">
	 <option value="">Select Type</option>
	@foreach($credentials_types as $ct)
       <option value="{{ $ct->id }}">{{ $ct->title }}</option>
    @endforeach
	</select>
 
</div>


<div class="form-group @if ($errors->has('host')) has-error @endif">
    {!! Form::label('host', 'Host') !!}
    {!! Form::text('host', @$host, ['class' => 'form-control', 'placeholder' => 'Host' ] ) !!}
    @if ($errors->has('host')) <p class="help-block">{{ $errors->first('host') }}</p> @endif
</div>

<div class="form-group @if ($errors->has('user')) has-error @endif">
    {!! Form::label('user', 'UserName') !!}
    {!! Form::text('user', @$user, ['class' => 'form-control', 'placeholder' => 'UserName' ] ) !!}
    @if ($errors->has('user')) <p class="help-block">{{ $errors->first('user') }}</p> @endif
</div>

<div class="form-group @if ($errors->has('password')) has-error @endif">
    {!! Form::label('password', 'Password') !!}
    {!! Form::text('password', @$password, ['class' => 'form-control', 'placeholder' => 'Password' ] ) !!}
    @if ($errors->has('password')) <p class="help-block">{{ $errors->first('password') }}</p> @endif
</div>

<div class="form-group @if ($errors->has('realtime_board_id')) has-error @endif">
    {!! Form::label('title', 'Sanbox/Live') !!}
       <select name="type" class="form-control">
	     <option value="">Select Type</option>
		 <option value="Live">Live</option>
		 <option value="Sandbox">Sandbox</option>
	</select>
</div>

resources/views/projects/_form_edit.blade.php
<!-- First Name Form Input -->
 

 

<div class="form-group @if ($errors->has('contact_type_id')) has-error @endif">
{!! Form::label('contact_type_id', 'Contact Type') !!}
 
 {{$errors->has('contact_type_id')}}
 
<?php $contact_types = \App\ContactType::get();?>
<select class="form-control" name="contact_type_id" id="contact_type_id" >
        @foreach($contact_types as $cat)
        <option value="{{$cat->id}}" <?php if($cat->id == \App\ContactType::where('id',$contact->contact_type_id)->first(["id"])->id){ echo 'SELECTED';}?>   >{{ $cat->title }}</option>
        @endforeach
      </select>
</div>



<!-- Contact Value Form Input -->
<div class="form-group @if ($errors->has('contact_value')) has-error @endif">
    {!! Form::label('contact_value', 'Contact Value') !!}
    {!! Form::text('contact_value', null, ['class' => 'form-control', 'placeholder' => 'Contact Value']) !!}
    @if ($errors->has('contact_value')) <p class="help-block">{{ $errors->first('contact_value') }}</p> @endif
</div>




<!-- Contact Value Form Input -->
<div class="form-group @if ($errors->has('contact_title')) has-error @endif">
    {!! Form::label('contact_title', 'Contact Title (optional)') !!}
    {!! Form::text('contact_title', null, ['class' => 'form-control', 'placeholder' => 'Contact Title']) !!}
    @if ($errors->has('contact_title')) <p class="help-block">{{ $errors->first('contact_title') }}</p> @endif
</div>

  
 

<!-- Permissions -->
@if(isset($user))
    @include('shared._permissions', ['closed' => 'true', 'model' => $user ])
@endif

resources/views/projects/_form_edit_credentials.blade.php
{!! Form::hidden('project_id', @$id, [] ) !!}
	
	
<div class="form-group @if ($errors->has('title')) has-error @endif">
    {!! Form::label('title', 'Type') !!}
 
		<?php $credentials_types = \App\CredentialsTypes::get(); ?>
	<select name="credentials_type_id" class="form-control">
	 <option value="">Select Type</option>
	@foreach($credentials_types as $ct)
       <option value="{{ $ct->id }}"  <?php if($item["credentials_type_id"] == $ct->id) { echo 'SELECTED';}?>  >{{ $ct->title }}</option>
    @endforeach
	</select>
	
 
</div>


<div class="form-group @if ($errors->has('host')) has-error @endif">
    {!! Form::label('host', 'Host') !!}
    {!! Form::text('host', @$item['host'], ['class' => 'form-control', 'placeholder' => 'Host' ] ) !!}
    @if ($errors->has('host')) <p class="help-block">{{ $errors->first('host') }}</p> @endif
</div>

<div class="form-group @if ($errors->has('user')) has-error @endif">
    {!! Form::label('user', 'UserName') !!}
    {!! Form::text('user', @$item['user'], ['class' => 'form-control', 'placeholder' => 'UserName' ] ) !!}
    @if ($errors->has('user')) <p class="help-block">{{ $errors->first('user') }}</p> @endif
</div>

<div class="form-group @if ($errors->has('password')) has-error @endif">
    {!! Form::label('password', 'Password') !!}
    {!! Form::text('password', @$item['password'], ['class' => 'form-control', 'placeholder' => 'Password' ] ) !!}
    @if ($errors->has('password')) <p class="help-block">{{ $errors->first('password') }}</p> @endif
</div>

<div class="form-group @if ($errors->has('realtime_board_id')) has-error @endif">
    {!! Form::label('title', 'Sanbox/Live') !!}
       <select name="type" class="form-control">
	     <option value="">Select Type</option>
		 <option value="Live" <?php if($item["type"] == 'Live') { echo 'SELECTED';}?>>Live</option>
		 <option value="Sandbox" <?php if($item["type"] == 'Sandbox') { echo 'SELECTED';}?>>Sandbox</option>
	</select>
</div>

resources/views/projects/_form_edit_trello.blade.php
<!-- First Name Form Input -->
 

<div class="form-group @if ($errors->has('title')) has-error @endif">
    {!! Form::label('title', 'Board Title') !!}
    {!! Form::text('title', $item['title'], ['class' => 'form-control ', 'placeholder' => 'Board Title' ] ) !!}
    @if ($errors->has('title')) <p class="help-block">{{ $errors->first('title') }}</p> @endif
</div>


 
    {!! Form::hidden('id', @$id, [] ) !!}
 


<div class="form-group @if ($errors->has('trello_board_id')) has-error @endif">
    {!! Form::label('trello_board_id', 'Trello Board Id') !!}
    {!! Form::text('trello_board_id', $item['trello_board_id'], ['class' => 'form-control', 'placeholder' => 'Trello Board Id' ] ) !!}
    @if ($errors->has('trello_board_id')) <p class="help-block">{{ $errors->first('trello_board_id') }}</p> @endif
</div>

resources/views/projects/_form_notes.blade.php
<!-- First Name Form Input -->
 

{!! Form::hidden('linked_id', $id, [] ) !!}
{!! Form::hidden('notes_type', 'project_development', [] ) !!}
 


@can('notes_permission')
<label for="notes_type" >Notes Type</label>
 
<div class="row">

<div class="col-md-4 col-lg-4">
<h3 style="padding:0;margin:0">Project Development</h3>
</div>
<div class="col-md-8 col-lg-8">

<input type="radio" name="notes_type" class="form-control" style="width:20%" value="project_development">
</div>
</div>


<div class="row">
<div class="col-md-4 col-lg-4">
<h3 style="padding:0;margin:0">Project Admin</h3>

</div>
<div class="col-md-8 col-lg-8">
<input type="radio" name="notes_type" class="form-control" style="width:20%" value="project_admin">

</div>
</div>
@endcan
 

 
 <div class="row">

<div class="col-md-4 col-lg-4">
 <label for="notes_type" >Pinned ? </label>
</div>
<div class="col-md-8 col-lg-8">

<input type="checkbox" name="pinned" class="form-control" style="width:20%" value="1">
</div>
</div>
 


 
<div class="form-group @if ($errors->has('host')) has-error @endif">
    {!! Form::label('notes', 'Note') !!}
    {!! Form::text('notes', '', ['class' => 'form-control', 'placeholder' => 'Notes' ] ) !!}
    @if ($errors->has('notes')) <p class="help-block">{{ $errors->first('notes') }}</p> @endif
</div>

resources/views/projects/_form_trello.blade.php
<!-- First Name Form Input -->
 

<div class="form-group @if ($errors->has('title')) has-error @endif">
    {!! Form::label('title', 'Board Title') !!}
    {!! Form::text('title', @$title, ['class' => 'form-control ', 'placeholder' => 'Board Title' ] ) !!}
    @if ($errors->has('title')) <p class="help-block">{{ $errors->first('title') }}</p> @endif
</div>


  
    {!! Form::hidden('project_id', @$id, [] ) !!}
 


<div class="form-group @if ($errors->has('trello_board_id')) has-error @endif">
    {!! Form::label('trello_board_id', 'Trello Board Id') !!}
    {!! Form::text('trello_board_id', @$trello_board_id, ['class' => 'form-control', 'placeholder' => 'Trello Board Id' ] ) !!}
    @if ($errors->has('trello_board_id')) <p class="help-block">{{ $errors->first('trello_board_id') }}</p> @endif
</div>

resources/views/projects/_navigation.blade.php
	<div class="row text-center">
					     <h2> <u><?php echo \App\Project::where('id',$id)->first(["project_title"])->project_title;?></u></h2>
					 </div>
<ul class="nav nav-tabs realTime">

@can('view_realtime_boards')
<li  class="<?php if(Request::path()=='project_details/realtimeboards/'.$id) { echo 'active';} ?>" ><a href="{{ URL::to('project_details/realtimeboards/'.$id) }}">RealTimeBoard </a><?php if(Request::path()=='project_details/realtimeboards/'.$id) {?><span>@can('edit_realtime_boards')<i class="fa fa-pencil" data-toggle="modal" data-target="#view"></i></span>@endcan<?php } ?></li>
@endcan


@can('view_trello_boards')
<li  class="<?php if(Request::path()=='project_details/trelloboards/'.$id) { echo 'active';} ?>" ><a href="{{ URL::to('project_details/trelloboards/'.$id) }}">Trello Boards </a><?php if(Request::path()=='project_details/trelloboards/'.$id) {?><span>@can('edit_trello_boards')<i class="fa fa-pencil" data-toggle="modal" data-target="#view"></i></span>@endcan<?php } ?></li>
@endcan


@can('view_credentials')
<li  class="<?php if(Request::path()=='project_details/credentials/'.$id) { echo 'active';} ?>" ><a href="{{ URL::to('project_details/credentials/'.$id) }}">Credentials </a><?php if(Request::path()=='project_details/credentials/'.$id) { ?><span>@can('edit_credentials')<i class="fa fa-pencil" data-toggle="modal" data-target="#view"></i></span>@endcan<?php } ?></li>
@endcan

@can('view_notes')
<li  class="<?php if(Request::path()=='project_details/notes/'.$id) { echo 'active';} ?>" ><a href="{{ URL::to('project_details/notes/'.$id) }}">Notes </a><?php if(Request::path()=='project_details/notes/'.$id) { ?><span>@can('edit_notes')<i class="fa fa-pencil" data-toggle="modal" data-target="#view"></i></span>@endcan<?php } ?></li>
@endcan



@can('view_notes')
<li  class="<?php if(Request::path()=='project_details/drives/'.$id) { echo 'active';} ?>" ><a href="{{ URL::to('project_details/drives/'.$id) }}">Google Drive </a></li>
@endcan



 
<li  class="<?php if(Request::path()=='board/project_details/cards/') { echo 'active';} ?>" ><a href="{{ URL::to('board/project_details/cards/') }}">Tasks</a></li>
 

 


</ul>	

resources/views/projects/_navigation_status.blade.php
 
<ul class="nav nav-tabs realTime">
 
<li  class="<?php if(Request::path()=='project_details/projects_by_status/0') { echo 'active';} ?>" ><a href="{{ URL::to('project_list/projects_by_status/0') }}">RealTimeBoard </a></li>
 


  
 


 


 


</ul>	

resources/views/projects/new.blade.php
@extends('layout.auth')
@section('title', 'Create')
@section('content')
@section('header')
@include('includes.header')
@show
<div id="wrapper"  >
   <div id="layout-static">
      <!---------- Static Sidebar Starts------------->			
      @section('sidebar')
      @include('includes.sidebar')
      @show
	  <!---------- Static Sidebar Ends------------->	
      <div class="row">
         	    @include('flash::message')
         <div class="col-md-6 page-action text-right">
            <a href="{{ route('projects.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Back</a>
         </div>
      </div>
      <div class="row">
         <div class="col-lg-10">
            {!! Form::open(['route' => ['projects.store'] ]) !!}
            @include('projects._form')
            <!-- Submit Form Button -->
            {!! Form::submit('Create', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
         </div>
      </div>
   </div>
</div>
@endsection