routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('ajax_test', 'HomeController@ajax_test')->name('ajax_test');

 //get tags via ajax
	Route::get('/get_tags', 'TutorialsController@get_tags')->name('get_tags');
	Route::get('/get_auth_skills', 'UserController@get_auth_skills')->name('get_auth_skills');
	
	
Route::get('/logout', 'HomeController@logout')->name('logout');


//Route::get('dashboard', ['middleware' => 'auth', 'uses' => 'UserController@getDashboard', 'as' => 'user.dashboard',]);
Route::group( ['middleware' => ['auth']], function() {
	Route::get('/users/{role}', 'UserController@users_by_role')->name('users_by_role');
    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
	Route::resource('contact_types', 'ContactTypeController');
	 
	Route::resource('credentials_types', 'CredentialsTypesController');
	Route::resource('urls_types', 'UrlsTypesController');
	Route::resource('urls', 'UrlsController');
	Route::get('/urls/analytics/{urlId}', 'UrlsController@get_analytics');
		
	Route::resource('payment_modes', 'PaymentModesController');
	Route::resource('payment_fee_types', 'PaymentFeeTypesController');
	
	Route::resource('designations', 'DesignationsController');
	Route::resource('card_issue_types', 'CardIssueTypesController');
	Route::resource('employee_designations', 'EmployeeDesignationsController');
	
	Route::post('add_issue_type', 'CardIssueTypesController@add_issue_type')->name('add_issue_type');
	
	Route::resource('tutorials', 'TutorialsController');
	//Route::get('add_tutorials', function () {    return view('tutorials.new');})->name("add_tutorials");
	Route::get('add_tutorials', 'TutorialsController@create')->name('add_tutorials');
	Route::post('get_tutorials', 'TutorialsController@get_tutorials')->name('get_tutorials');
	
	Route::get('get_tutorials_list', 'TutorialsController@get_tutorials_list')->name('get_tutorials_list');
	
	Route::resource('contacts', 'ContactController');
	Route::resource('projects', 'ProjectController');
	
	Route::resource('realtimeboards', 'ProjectRealTimeController');
	Route::resource('trelloboards', 'ProjectTrelloController');
	Route::resource('credentials', 'ProjectCredentialsController');
	Route::resource('notes', 'ProjectNotesController');
	
	Route::get('/get_auth_skills', 'UserController@get_auth_skills')->name('get_auth_skills');
	
   
	
	Route::get('/projects_list/projects_by_status/{status}', 'ProjectController@projects_by_status')->name('projects_by_status');
	Route::get('/project_details/realtimeboards/{id}', 'ProjectController@show_realtimeboard')->name('show_realtimeboard');
	Route::get('/project_details/trelloboards/{id}', 'ProjectController@show_trelloboard')->name('show_trelloboard');
	Route::get('/project_details/credentials/{id}', 'ProjectController@show_credentials')->name('show_credentials');
	Route::get('/project_details/notes/{id}', 'ProjectController@show_notes')->name('show_notes');
	Route::get('/project_details/drives/{id}', 'ProjectController@show_google_drives')->name('show_google_drives');
	Route::get('/project_details/cards/{id}', 'BoardController@show_cards')->name('show_cards');
	
	
	Route::get('/users/show_edit_user_profile/{id}', 'UserController@show_edit_user_profile')->name('show_edit_user_profile');
	Route::post('/users/update_edit_user_profile/', 'UserController@update_edit_user_profile')->name('update_edit_user_profile');
	
	Route::post('/projects_by_employee/', 'ProjectController@projects_by_employee')->name('projects_by_employee');
	
	//contacts starts
	Route::get('/contacts/{role}/{linked_id}', 'ContactController@index')->name('get_contacts');
	
	
});


 
Route::get('downloadExcel/{role}/xls', 'UserController@downloadExcelByRole');
Route::get('downloadExcel/xls', 'UserController@downloadExcelAll');
 
Route::get('downloadExcelProject/{role}/xls', 'ProjectController@downloadExcelByRole');
Route::get('downloadExcelProject/xls', 'ProjectController@downloadExcelAll');

Route::post('importExcel', 'ExportController@importExcel');




Route::get('register', ['middleware' => 'guest', 'uses' => 'UserController@getRegister', 'as' => 'auth.register',]);
Route::post('register', ['middleware' => 'guest', 'uses' => 'UserController@postRegister',]);
Route::get('dashboard', ['middleware' => 'auth', 'uses' => 'UserController@getDashboard', 'as' => 'user.dashboard',]);
Route::get('profile', ['middleware' => 'auth', 'uses' => 'UserController@getProfile', 'as' => 'user.profile',]);
Route::get('activity', ['middleware' => 'auth', 'uses' => 'UserActivityController@getUserActivity', 'as' => 'user.activity',]);

Route::post('postBoard', ['middleware' => 'auth', 'uses' => 'BoardController@postBoard',]);
Route::post('update-board-favourite', ['middleware' => 'auth', 'uses' => 'BoardController@updateBoardFavourite',]);

/**
 * Board
 */
Route::group(
    ['prefix' => 'board'],
    function () {
        
		Route::post('/postListName', ['uses' => 'ListController@postListName',]);
        
		Route::post('/delete-list', ['uses' => 'ListController@deleteList',]);
        
		Route::post('/update-list-name', ['uses' => 'ListController@updateListName',]);

        Route::post('/postCard', ['uses' => 'CardController@postCard',]);
        
		Route::post('/getPusherData', ['uses' => 'BoardController@getPusherData',]);
				
        Route::post('/changeCardList', ['uses' => 'CardController@changeCardList',]);
        
		Route::post('/deleteCard', ['uses' => 'CardController@deleteCard',]);
        
		Route::post('/getCardDetail', ['uses' => 'CardController@getCardDetail',]);
        
		Route::post('/update-card-data', ['uses' => 'CardController@updateCardData',]);

        Route::post('/save-comment', ['uses' => 'CommentController@saveComment',]);

        Route::post('/save-task', ['uses' => 'TaskController@saveTask',]);
        
		Route::post('/delete-task', ['uses' => 'TaskController@deleteTask',]);
        
		Route::post('/update-task-completed', ['uses' => 'TaskController@updateTaskCompleted',]);
		
		Route::post('/file_uploader', ['uses' => 'FileUploader@file_uploader',])->name('file_uploader');

        Route::get('/{id?}', ['middleware' => 'auth', 'uses' => 'BoardController@getBoardDetail', 'as' => 'user.boardDetail',]);
		
 
		
		Route::get('/project_details/cards/{id?}', ['middleware' => 'auth', 'uses' => 'BoardController@getBoardDetailProject', 'as' => 'user.boardDetail',]);
		
		Route::post('/cards-filter', ['middleware' => 'auth', 'uses' => 'BoardController@getBoardDetailFiltered', 'as' => 'user.cards-filter',]);
		
		Route::get('/duedate/{id?}', ['middleware' => 'auth', 'uses' => 'BoardController@getBoardDetail', 'as' => 'user.boardDetail',]);
        
		Route::post('create-user-activity', ['uses' => 'UserActivityController@createUserActivity']);
    }
);

/**
 * Password Reset
 */
Route::group(
    ['prefix' => 'password'],
    function () {
        // Password reset link request routes...
        Route::get('/email', 'Auth\PasswordController@getEmail');
        Route::post('/email', 'Auth\PasswordController@postEmail');

        // Password reset routes...
        Route::get('/reset/{token}', 'Auth\PasswordController@getReset');
        Route::post('/reset', 'Auth\PasswordController@postReset');
    }
);

Route::post('create-user-activity', ['uses' => 'UserActivityController@createUserActivity']);



Route::get('test/{cardId}', function ($cardId) {
	 
    event(new App\Events\StatusLiked($cardId));
    return "Event has been sent!";
});
 

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') {{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
{{--    <link href="{{ asset('css/app.css') }}" rel="stylesheet">--}}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css">

    <style>
        .result-set { margin-top: 1em }
    </style>
    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        @if (Auth::check())
                            @can('view_users')
                                <li class="{{ Request::is('users*') ? 'active' : '' }}">
                                    <a href="{{ route('users.index') }}">
                                        <span class="text-info glyphicon glyphicon-user"></span> Users
                                    </a>
                                </li>
                            @endcan

                            @can('view_posts')
                                <li class="{{ Request::is('posts*') ? 'active' : '' }}">
                                    <a href="{{ route('posts.index') }}">
                                        <span class="text-success glyphicon glyphicon-text-background"></span> Posts
                                    </a>
                                </li>
                            @endcan
                        @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                          
                        @else

                            @can('view_roles')
                            <li class="{{ Request::is('roles*') ? 'active' : '' }}">
                                <a href="{{ route('roles.index') }}">
                                    <span class="text-danger glyphicon glyphicon-lock"></span> Roles
                                </a>
                            </li>
                            @endcan

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }}
                                    <span class="label label-success">{{ Auth::user()->roles->pluck('name')->first() }}</span>
                                    <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            <i class="glyphicon glyphicon-log-out"></i> Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div id="flash-msg">
                @include('flash::message')
            </div>
            @yield('content')
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    @stack('scripts')

    <script>
        $(function () {
            // flash auto hide
            $('#flash-msg .alert').not('.alert-danger, .alert-important').delay(6000).slideUp(500);
        })
    </script>
</body>
</html>

resources/views/layouts/app_task.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dingo</title>
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/jquery-ui.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap-editable.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/sweetalert.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/magic-check.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/selectize.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/sidebar.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/animation.css') }}" rel="stylesheet"/>
    <script src="{{ URL::asset('admin/img-uploads/js/jquery.min.js')}}"></script>
    <script src="{{ URL::asset('admin/js/bootstrap-multiselect.js')}}"   ></script>
	<link href="{{ URL::asset('admin/css/bootstrap-multiselect.css')}}" type="text/css" rel="stylesheet">
	
	   <!--------Assets For Time Picker and date&time picker------------------>
 
    <script>
        var assetUserImage = "{{ asset('img/user_1.jpg') }}";
    </script>
</head>
<body>
    <!---<div class="spinner">
      <div class="rect1"></div>
      <div class="rect2"></div>
      <div class="rect3"></div>
      <div class="rect4"></div>
      <div class="rect5"></div>
    </div>-->
    @include('layouts.partials.modal')
    @include('layouts.partials.navigation')
    @yield('content')

 
    <script src="{{ asset('js/jquery-ui.js') }}"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/bootstrap-editable.min.js') }}"></script>
    <script src="{{ asset('js/sweetalert.min.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
    <!--<script src="{{ asset('js/ajax-loading.js') }}"></script>-->
    <script src="{{ asset('js/selectize.js') }}"></script>
    <script src="{{ asset('js/board.js') }}"></script>
 
    <script src="{{ asset('js/sidebar.js') }}"></script>
    <script src="{{ asset('js/typed.min.js') }}"></script>
</body>
</html>

resources/views/layouts/app_task_angular.blade.php
<html>
   
   <head>
   
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <title>@yield('title')</title>
	        <!-- Font Awesome -->
	   <link href='http://fonts.googleapis.com/css?family=RobotoDraft:300,400,400italic,500,700' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,400italic,600,700' rel='stylesheet' type='text/css'>
      <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
	  <link rel="stylesheet" href="{{ URL::asset('admin/css/bootstrap.min.css')}}"> 
       <link href="{{ URL::asset('admin/css/styles.css')}}" type="text/css" rel="stylesheet">
	   <link href="{{ URL::asset('admin/css/main-style.css')}}" type="text/css" rel="stylesheet">
	   <link href="{{ URL::asset('admin/css/custom_task.css')}}" type="text/css" rel="stylesheet">
	   
	   
	   <!--------Assets For Image Uploading------------------->
	   <link href="{{ URL::asset('admin/img-uploads/css/style.css')}}" rel="stylesheet">
       <script src="{{ URL::asset('admin/img-uploads/js/jquery.min.js')}}"></script>
     	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
		
		
		
		<!-------------------- uploadeer assets--------->
		 <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
		 <link href="{{ URL::asset('upload/css/jquery.fileuploader.min.css')}}" media="all" rel="stylesheet">
		 <link href="{{ URL::asset('upload/css/jquery.fileuploader-theme-thumbnails.css')}}" media="all" rel="stylesheet">
	   
		 <script src="{{ URL::asset('upload/js/jquery.fileuploader.min.js')}}" type="text/javascript"></script>
		 <script src="{{ URL::asset('upload/js/custom.js')}}" type="text/javascript"></script>
	<!----------------uploader ends ----------->
	
			
 
 
 
 
	  <style>
	  
	  multiselect {
    display:block;
}
multiselect .btn {
    width: 100%;
    background-color: #FFF;
}
multiselect .btn.error{
    border: 1px solid #da4f49 !important;
}
multiselect .dropdown-menu {
    max-height: 300px;
    overflow-y: auto;
}
multiselect .dropdown-menu {
    width: 100%;
    box-sizing: border-box;
    padding: 2px;
}
multiselect .dropdown-menu > li > a {
    padding: 3px 10px;
    cursor:pointer;
}

</style>
	      
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/jquery-ui.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap-editable.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/sweetalert.css') }}" rel="stylesheet"/>
    <link href="{{ asset('css/magic-check.min.css') }}" rel="stylesheet"/>
 
    <link href="{{ asset('css/selectize.css') }}" rel="stylesheet"/>
 
    <link href="{{ asset('css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet"/>
 
    <link href="{{ asset('css/animation.css') }}" rel="stylesheet"/>
 
   
    <script src="{{ URL::asset('admin/js/bootstrap-multiselect.js')}}"   ></script>
	  <link href="{{ URL::asset('admin/css/bootstrap-multiselect.css')}}" type="text/css" rel="stylesheet">

 
	       <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
   </head>
   
   <body onload='hashchange()'; onhashchange="hashchange()">
 
	      <!---------- Static Sidebar Starts------------------------------------------------------------------------------------------------------------->			

	
  
      
 
         @yield('content')
       

	  
	  

 							<!-- Load Bootstrap -->  
      <script src="{{ URL::asset('admin/js/enquire.min.js')}}"></script> 									<!-- Enquire for Responsiveness -->
      <script src="{{ URL::asset('admin/plugins/nanoScroller/js/jquery.nanoscroller.min.js')}}"></script> <!-- nano scroller --> 
      <script src="{{ URL::asset('admin/js/application.js')}}"></script> 
	  
	  
	<script src="{{ asset('js/jquery-ui.js') }}"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/bootstrap-editable.min.js') }}"></script>
    <script src="{{ asset('js/sweetalert.min.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
   <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
    <!--<script src="{{ asset('js/ajax-loading.js') }}"></script>-->
    <script src="{{ asset('js/selectize.js') }}"></script>
    <script src="{{ asset('js/board.js') }}"></script>
 
    <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
    
    <script src="{{ asset('js/typed.min.js') }}"></script>
	  
	   
	   <script>
  $('.toggle-button').click(function(e){
    $('#myDiv').toggleClass('fullscreen');  
});
 </script>
	  <!---------script for checkbox table------------->
	  <script type='text/javascript'> 
        $(window).load(function(){
           $('#selectAll').click(function (e) {
               $(this).closest('table').find('td input:checkbox').prop('checked', this.checked);
            });
        }); 
     </script>
   	 
	 <script>
	 $(document).ready(function () {
        $('.checkAll').on('click', function () {
           $(this).closest('table').find('tbody :checkbox')
             .prop('checked', this.checked)
             .closest('tr').toggleClass('selected', this.checked);
        });

        $('tbody :checkbox').on('click', function () {
            $(this).closest('tr').toggleClass('selected', this.checked); //Classe de seleção na row
            $(this).closest('table').find('.checkAll').prop('checked', ($(this).closest('table').find('tbody :checkbox:checked').length == $(this).closest('table').find('tbody :checkbox').length)); //Tira / coloca a seleção no .checkAll
        });
      });  
	  </script>
	  
 
<script>
$('div.alert').not('.alert-important').delay(3000).fadeOut(350);
</script>


<script>
function hashchange(event)
{
	
	
	var hash =window.location.hash;
	 hash = hash.replace("#", "");
	  if(hash!='')
	  {
    document.getElementById('card_detail_'+hash).click();
	  }

 
 
}
hashchange();
</script>
   </body>
</html>